#!/usr/bin/env bash
# kernel-bump — generate the throwaway `--kernel` fixture corpus (kernel-consumer plan Task 4).
#
# DEV-HOST ONLY. Tests NEVER invoke gpg/xz — they read the committed bytes under gen/. A re-run
# produces a FRESH corpus (throwaway keys are random); tests bind to the committed bytes via
# gen/MANIFEST.toml (fingerprints + shas recorded per run — never hardcoded in tests).
#
# Requires: gpg 2.4.x (pinned toolchain gpg 2.4.9 / libgcrypt 1.12.2), xz, python3. No network.
# Conventions mirror crates/cashew/tests/fixtures/gen.sh (ephemeral loopback GNUPGHOME; all material
# stamped at a faked GENTIME; evaluated by tests at fixture_now = GENTIME + 100000).
#
# Shapes produced:
#   signer.asc              throwaway RSA-4096 [SC] primary (the real kernel-dev shape), §5.0-pruned export
#   payload.tar             deterministic tiny "kernel source" tar (GNU shape, fixed mtime/owner/sort)
#   payload.tar.xz          xz -9 of payload.tar (the fetch fixture)
#   payload.tar.sign        armored detached sig by signer over the UNCOMPRESSED tar (kernel.org shape)
#   unpinned.tar.sign       the same tar signed by a SECOND throwaway key (absent from any keyring)
#   payload-tampered.tar.xz valid xz of a one-byte-flipped tar (signature must fail)
#   bomb.tar.xz             4 MiB of zeros compressed tiny (over a 1 MiB test ceiling)
#   crafted.sign            armored shape, garbage packet bytes (cashew Malformed; process survives)

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$here/gen"
rm -rf "$out"
mkdir -p "$out"

GNUPGHOME="$(mktemp -d)"
export GNUPGHOME
chmod 700 "$GNUPGHOME"
echo "allow-loopback-pinentry" > "$GNUPGHOME/gpg-agent.conf"
trap 'gpgconf --kill gpg-agent >/dev/null 2>&1 || true; rm -rf "$GNUPGHOME"' EXIT

GENTIME=1781000000
gpg_q() {
  gpg --batch --quiet --yes --pinentry-mode loopback --passphrase '' \
      --cert-digest-algo SHA256 --faked-system-time "${GENTIME}!" "$@"
}
prune_export() {  # <fpr> <keep-uid-expr> <outfile>
  gpg_q --export-options export-minimal,no-export-attributes \
        --export-filter "keep-uid=$2" \
        --export-filter 'drop-subkey=usage=e' \
        --armor --export "$1" > "$3"
}
quick_key() {  # <uid> -> prints fingerprint ; RSA-4096 [SC] primary, no passphrase
  gpg_q --quick-generate-key "$1" rsa4096 sign never >/dev/null 2>&1
  gpg --batch --with-colons --list-keys "$1" | awk -F: '/^fpr:/ {print $10; exit}'
}

echo "generating throwaway RSA-4096 keys…" >&2
FS=$(quick_key "kernel-bump-signer <signer@example.invalid>")
FU=$(quick_key "kernel-bump-unpinned <unpinned@example.invalid>")

prune_export "$FS" "mbox=signer@example.invalid" "$out/signer.asc"

VER="6.99.1"
# Deterministic payload tar — the GNU shape the source-drop rule pins (--format=gnu), fixed
# mtime/owner/sort so the bytes are stable given the content.
workdir="$(mktemp -d)"
mkdir -p "$workdir/linux-$VER"
printf 'kernel-bump fixture tree — not a kernel\n' > "$workdir/linux-$VER/README-fixture"
tar --format=gnu --sort=name --owner=0 --group=0 --numeric-owner --mtime="@${GENTIME}" \
    -C "$workdir" -cf "$out/payload.tar" "linux-$VER"
rm -rf "$workdir"
xz -9 --keep --stdout "$out/payload.tar" > "$out/payload.tar.xz"

# Detached armored signatures over the UNCOMPRESSED tar (one sig covers .gz/.xz — kernel.org shape).
gpg_q --default-key "$FS" --digest-algo SHA512 --detach-sign --armor \
      --output "$out/payload.tar.sign" "$out/payload.tar"
gpg_q --default-key "$FU" --digest-algo SHA512 --detach-sign --armor \
      --output "$out/unpinned.tar.sign" "$out/payload.tar"

# Tampered: flip one content byte of the tar, re-xz — a VALID .xz whose decompressed bytes are not
# the signed bytes (BadSignature at finalize, after a clean decompress).
python3 - "$out" <<'PY'
import sys, pathlib
out = pathlib.Path(sys.argv[1])
b = bytearray((out / "payload.tar").read_bytes())
b[512] ^= 0x01
(out / "_tampered.tar").write_bytes(bytes(b))
PY
xz -9 --stdout "$out/_tampered.tar" > "$out/payload-tampered.tar.xz"
rm -f "$out/_tampered.tar"

# Decompression bomb: 4 MiB of zeros → a tiny .xz that exceeds a 1 MiB test ceiling on decode.
head -c 4194304 /dev/zero | xz -9 > "$out/bomb.tar.xz"

# Crafted .sign: correct armor framing, garbage packet bytes (first byte 0x00 = not a packet header)
# — cashew classifies Malformed via the catch_unwind-backed parse; the bump must survive + pin nothing.
python3 - "$out" <<'PY'
import base64, pathlib, sys
out = pathlib.Path(sys.argv[1])
garbage = bytes(range(256)) * 4
body = base64.encodebytes(garbage).decode()
out.joinpath("crafted.sign").write_text(
    "-----BEGIN PGP SIGNATURE-----\n\n" + body + "-----END PGP SIGNATURE-----\n"
)
PY

sha() { sha256sum "$1" | cut -d' ' -f1; }
{
  echo "# Auto-generated by gen.sh — throwaway --kernel fixture corpus (FRESH per run)."
  echo "# Tests bind to these committed bytes via this manifest — never hardcode fingerprints/shas."
  echo "gen_time    = $GENTIME"
  echo "fixture_now = $((GENTIME + 100000))"
  echo "version     = \"$VER\""
  echo ""
  echo "[keys]"
  echo "signer   = \"$FS\""
  echo "unpinned = \"$FU\""
  echo ""
  echo "[sha256]"
  for f in signer.asc payload.tar payload.tar.xz payload.tar.sign unpinned.tar.sign \
           payload-tampered.tar.xz bomb.tar.xz crafted.sign; do
    echo "\"$f\" = \"$(sha "$out/$f")\""
  done
} > "$out/MANIFEST.toml"

echo "gen.sh: wrote $(ls "$out" | wc -l) files to gen/" >&2
